variable "env" {}
variable "subnet_ids" {}
variable "allow_cidr" {}
variable "main_vpc" {}
#variable "internal" {}
#variable "subnets_name" {}
variable "app_port" {}
variable "component" {}
variable "max_size" {}
variable "min_size" {}
variable "desired_capacity" {}
variable "instance_type" {}
variable "allow_workstation_cidr" {}
